const $=id=>document.getElementById(id);
const sourceEls={date:'sDate',track:'sTrack',number:'sNumber',seller:'sSeller',buyer:'sBuyer',net:'sNet',tax:'sTax',gross:'sGross'};
const state={file:null,mode:'auto',items:[],sources:{},candidates:{},qr:[],barcodes:[],ocrTexts:[],qrBuyerAbsent:false,ocrConfidence:0};
const money=n=>'$'+Math.max(0,Math.round(Number(n)||0)).toLocaleString('zh-TW');
const N=v=>Math.max(0,Math.round(Number(v)||0));
function setSource(k,txt){state.sources[k]=txt||'—'; const e=$(sourceEls[k]); if(e)e.textContent=state.sources[k];}
function addCandidate(k,value,source,score){if(value===undefined||value===null||value==='')return; (state.candidates[k]??=[]).push({value:String(value),source,score});}
function normalizeLine(s){return String(s||'').replace(/[：]/g,':').replace(/[，]/g,',').replace(/[－—–]/g,'-').replace(/\u3000/g,' ').replace(/\s+/g,' ').trim();}
function fixDigits(s){return String(s||'').toUpperCase().replace(/O|Q|D/g,'0').replace(/[IL|]/g,'1').replace(/Z/g,'2').replace(/S/g,'5').replace(/B/g,'8').replace(/[^0-9]/g,'');}
function validBan(b){b=fixDigits(b); if(!/^\d{8}$/.test(b))return false; const w=[1,2,1,2,1,2,4,1]; let sum=0; for(let i=0;i<8;i++){const p=Number(b[i])*w[i]; sum+=Math.floor(p/10)+(p%10);} return sum%5===0;}
function banBadge(b){if(!b)return '未登載'; return validBan(b)?'有效統編':'⚠ 檢查碼異常';}
function parseDateToken(s){s=normalizeLine(s); let m=s.match(/(?:中華民國)?\s*(\d{2,3})\s*年\s*(\d{1,2})\s*月\s*(\d{1,2})\s*日/); if(m){let y=+m[1]+1911; return `${y}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;} m=s.match(/(20\d{2})[\/\-.年]\s*(\d{1,2})[\/\-.月]\s*(\d{1,2})/); if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`; return ''}
function numberFrom(s){return N(String(s||'').replace(/[^0-9.-]/g,''));}
function parseTaiwanQR(q){q=String(q||'').trim(); if(q.length<53)return null; const inv=q.slice(0,10); if(!/^[A-Z]{2}\d{8}$/.test(inv))return null; const roc=q.slice(10,17), subtotalHex=q.slice(21,29), totalHex=q.slice(29,37), buyer=q.slice(37,45), seller=q.slice(45,53); if(!/^\d{7}$/.test(roc))return null; const y=parseInt(roc.slice(0,3),10)+1911, m=roc.slice(3,5), d=roc.slice(5,7); const net=parseInt(subtotalHex,16), gross=parseInt(totalHex,16); return {track:inv.slice(0,2),number:inv.slice(2),date:`${y}-${m}-${d}`,buyer:/^0{8}$/.test(buyer)?'':buyer,seller,net:Number.isFinite(net)?net:0,gross:Number.isFinite(gross)?gross:0,tax:Number.isFinite(net)&&Number.isFinite(gross)?Math.max(0,gross-net):0};}
async function imageToCanvas(file,maxDim=2200){const bmp=await createImageBitmap(file); const scale=Math.min(1,maxDim/Math.max(bmp.width,bmp.height)); const c=document.createElement('canvas'); c.width=Math.round(bmp.width*scale); c.height=Math.round(bmp.height*scale); c.getContext('2d',{willReadFrequently:true}).drawImage(bmp,0,0,c.width,c.height); bmp.close?.(); return c;}
function cropCanvas(src,x,y,w,h){const c=document.createElement('canvas'); c.width=Math.max(1,Math.round(w)); c.height=Math.max(1,Math.round(h)); c.getContext('2d',{willReadFrequently:true}).drawImage(src,x,y,w,h,0,0,c.width,c.height); return c;}
function enhanceCanvas(src){const c=document.createElement('canvas'); c.width=src.width;c.height=src.height; const ctx=c.getContext('2d',{willReadFrequently:true}); ctx.drawImage(src,0,0); const im=ctx.getImageData(0,0,c.width,c.height),d=im.data; let sum=0,count=0; for(let i=0;i<d.length;i+=16){sum+=(d[i]+d[i+1]+d[i+2])/3;count++;} const avg=sum/Math.max(1,count),thr=Math.max(120,Math.min(205,avg*0.88)); for(let i=0;i<d.length;i+=4){const g=0.299*d[i]+0.587*d[i+1]+0.114*d[i+2]; const v=g>thr?255:0;d[i]=d[i+1]=d[i+2]=v;} ctx.putImageData(im,0,0); return c;}
function scanQrRegion(canvas,x,y,w,h){try{const ctx=canvas.getContext('2d',{willReadFrequently:true}); const data=ctx.getImageData(x,y,w,h); const r=jsQR(data.data,w,h,{inversionAttempts:'attemptBoth'}); return r?.data||'';}catch{return ''}}
function scanQRCodes(canvas){const W=canvas.width,H=canvas.height,regs=[[0,0,W,H],[0,Math.floor(H*.4),W,Math.floor(H*.6)],[0,Math.floor(H*.45),Math.floor(W*.55),Math.floor(H*.55)],[Math.floor(W*.45),Math.floor(H*.45),Math.floor(W*.55),Math.floor(H*.55)]]; const out=[]; for(const [x,y,w,h] of regs){const s=scanQrRegion(canvas,x,y,Math.min(w,W-x),Math.min(h,H-y)); if(s&&!out.includes(s))out.push(s);} return out;}
async function scanBarcodes(canvas){const out=[]; if(!('BarcodeDetector' in window))return out; try{const formats=await BarcodeDetector.getSupportedFormats(); const use=formats.filter(x=>['code_128','code_39','ean_13','ean_8','itf','qr_code'].includes(x)); const det=new BarcodeDetector({formats:use}); const rs=await det.detect(canvas); for(const r of rs){if(r.rawValue&&!out.includes(r.rawValue))out.push(r.rawValue)}}catch{} return out;}
function parseOCR(text,sourceBase,baseScore=70){const lines=String(text||'').split(/\r?\n/).map(normalizeLine).filter(Boolean); const joined=lines.join('\n'); const invNumbers=new Set();
 for(const line of lines){let m=line.match(/\b([A-Z]{2})\s*-?\s*([0-9OQDISBLZ|]{8})\b/i); if(m){const no=fixDigits(m[2]); if(no.length===8){addCandidate('track',m[1].toUpperCase(),sourceBase+'：發票號碼',baseScore+12);addCandidate('number',no,sourceBase+'：發票號碼',baseScore+12);invNumbers.add(no);}}
 const dt=parseDateToken(line); if(dt)addCandidate('date',dt,sourceBase+'：日期',baseScore+8);
 m=line.match(/(?:賣\s*方|銷\s*售\s*人|營\s*業\s*人)\s*(?:統一編號|統編|編號)?\s*:?\s*([0-9OQDISBLZ|]{8})/i); if(m){const b=fixDigits(m[1]);if(validBan(b))addCandidate('seller',b,sourceBase+'：賣方標籤',baseScore+22);}
 m=line.match(/(?:買\s*方|買\s*受\s*人)\s*(?:統一編號|統編|編號)?\s*:?\s*([0-9OQDISBLZ|]{8})/i); if(m){const b=fixDigits(m[1]);if(validBan(b))addCandidate('buyer',b,sourceBase+'：買方標籤',baseScore+22);}
 m=line.match(/(?:銷售額|未稅(?:金額)?|小計)\s*:?\s*(?:NT\$?|\$)?\s*([0-9,]+)/i); if(m)addCandidate('net',numberFrom(m[1]),sourceBase+'：銷售額標籤',baseScore+16);
 m=line.match(/(?:營業稅額|稅額|VAT)\s*:?\s*(?:NT\$?|\$)?\s*([0-9,]+)/i); if(m)addCandidate('tax',numberFrom(m[1]),sourceBase+'：稅額標籤',baseScore+16);
 m=line.match(/(?:總計|合計|總金額|含稅(?:總額|金額)?|應付)\s*:?\s*(?:NT\$?|\$)?\s*([0-9,]+)/i); if(m)addCandidate('gross',numberFrom(m[1]),sourceBase+'：總計標籤',baseScore+16);
 }
 for(let i=0;i<lines.length-1;i++){const cur=lines[i],next=lines[i+1]; if(/^(賣方|銷售人|營業人)(?:統一編號|統編|編號)?\s*:?$/i.test(cur)){const b=fixDigits(next);if(validBan(b))addCandidate('seller',b,sourceBase+'：賣方下一行',baseScore+14)} if(/^(買方|買受人)(?:統一編號|統編|編號)?\s*:?$/i.test(cur)){const b=fixDigits(next);if(validBan(b))addCandidate('buyer',b,sourceBase+'：買方下一行',baseScore+14)}}
 const all=[...joined.matchAll(/(?:^|[^A-Z0-9])([0-9OQDISBLZ|]{8})(?=$|[^A-Z0-9])/gi)].map(m=>fixDigits(m[1])); for(const b of all){if(validBan(b)&&!invNumbers.has(b))addCandidate('genericBan',b,sourceBase+'：未標示統編候選',baseScore-25)}
}
function best(k){const a=(state.candidates[k]||[]).slice().sort((x,y)=>y.score-x.score); return a[0]||null;}
function mergeGenericBans(){const gs=(state.candidates.genericBan||[]).slice().sort((a,b)=>b.score-a.score); const seller=best('seller'),buyer=best('buyer'); for(const g of gs){if(seller?.value===g.value||buyer?.value===g.value)continue; const company=fixDigits(companyBan.value); if(company&&g.value===company){if(state.qrBuyerAbsent) continue; addCandidate('buyer',g.value,g.source+'＋申報單位比對',58);}}}
function chooseFields(){mergeGenericBans(); for(const k of ['date','track','number','seller','net','tax','gross']){const b=best(k); if(b){$(k).value=b.value;setSource(k,b.source)}} if(state.qrBuyerAbsent){buyer.value='';setSource('buyer','QR：未登載')}else{const b=best('buyer'); if(b){buyer.value=b.value;setSource('buyer',b.source)}else{buyer.value='';setSource('buyer','未辨識')}}}
function addQR(q){const p=parseTaiwanQR(q); if(!p)return false; ['date','track','number','seller','net','tax','gross'].forEach(k=>addCandidate(k,p[k],'QR Code',100)); if(p.buyer)addCandidate('buyer',p.buyer,'QR Code',100); else state.qrBuyerAbsent=true; return true;}
function addBarcode(raw){const m=String(raw||'').toUpperCase().match(/([A-Z]{2})[- ]?(\d{8})/); if(m){addCandidate('track',m[1],'一維條碼',78);addCandidate('number',m[2],'一維條碼',78)}}
function validateRecognition(){const company=fixDigits(companyBan.value),s=fixDigits(seller.value),b=fixDigits(buyer.value),tr=track.value.trim().toUpperCase(),no=fixDigits(number.value),netv=N(net.value),taxv=N(tax.value),grossv=N(gross.value); const issues=[],oks=[];
 if(!/^[A-Z]{2}$/.test(tr)||!/^\d{8}$/.test(no))issues.push('發票字軌／號碼不完整'); else oks.push('發票號碼格式完整');
 if(!s)issues.push('賣方統編缺漏'); else if(!validBan(s))issues.push('賣方統編檢查碼異常'); else oks.push('賣方統編通過檢查碼');
 if(b){if(!validBan(b))issues.push('買方統編檢查碼異常'); else oks.push('買方統編通過檢查碼')} else oks.push('買方統編未登載（保持空白）');
 if(grossv&&netv&&taxv){if(netv+taxv===grossv)oks.push('金額：未稅＋稅額＝總額');else issues.push('金額不一致：未稅＋稅額 ≠ 總額'); if(taxv>0&&Math.abs(taxv-Math.round(netv*.05))<=1)oks.push('5% 稅額交叉檢查合理');} else issues.push('未稅／稅額／總額尚未完整');
 let role='unknown',eligible=false,reason='';
 if(company&&s===company&&b===company){role='unknown';reason='賣方與買方都等於申報單位，資料異常';issues.push(reason)}
 else if(company&&b===company){role='purchase';eligible=true;reason='買方統編＝申報單位統編 → 進項'}
 else if(company&&s===company){role='sales';eligible=true;reason='賣方統編＝申報單位統編 → 銷項'}
 else if(company&&s&&b&&s!==company&&b!==company){role='ineligible';reason='賣方與買方統編皆非申報單位 → 不可申報';issues.push(reason)}
 else if(company){role='unknown';reason='缺少可證明與申報單位相符的買方／賣方統編 → 待確認';issues.push(reason)}
 else {role='unknown';reason='尚未設定申報單位統編';issues.push(reason)}
 direction.value=role; direction.disabled=true;
 const sourceConflict=[]; for(const k of ['number','seller','buyer','net','tax','gross']){const vals=[...new Set((state.candidates[k]||[]).map(x=>x.value).filter(Boolean))]; if(vals.length>1)sourceConflict.push(`${k} 有 ${vals.length} 個不同來源值`)} if(sourceConflict.length)issues.push(...sourceConflict);
 const critical=[/^[A-Z]{2}$/.test(tr),/^\d{8}$/.test(no),!!s&&validBan(s),grossv>0,netv>=0,taxv>=0]; let score=Math.round(critical.filter(Boolean).length/critical.length*70); if(state.qr.some(add=>parseTaiwanQR(add)))score+=15; if(state.ocrConfidence>=80)score+=8; if(!sourceConflict.length)score+=7; if(issues.some(x=>x.includes('檢查碼異常')||x.includes('金額不一致')))score-=15; score=Math.max(0,Math.min(100,score)); qualityScore.textContent=score;
 checks.innerHTML=[...oks.map(x=>`<div class="check"><span>✅ ${x}</span><b>PASS</b></div>`),...issues.map(x=>`<div class="check"><span>⚠️ ${x}</span><b>REVIEW</b></div>`)].join('');
 filingDecision.className=eligible?'ok':(role==='ineligible'?'bad':'warn'); filingDecision.textContent=(eligible?'✅ ':'⚠️ ')+reason;
 conflicts.className=issues.length?'warn':'ok'; conflicts.textContent=issues.length?'⚠ '+issues.join('；'):'✓ 跨來源與欄位檢查通過。'; return {role,eligible,issues,score,reason};}
function renderSourceDetail(){const keys=[['date','日期'],['track','字軌'],['number','號碼'],['seller','賣方統編'],['buyer','買方統編'],['net','未稅'],['tax','稅額'],['gross','總額']]; sourceDetail.innerHTML=keys.map(([k,n])=>{const a=(state.candidates[k]||[]).slice().sort((x,y)=>y.score-x.score).slice(0,3); if(k==='buyer'&&state.qrBuyerAbsent)return `<div class="source-grid"><b>${n}</b><span>未登載</span><span>QR 100</span></div>`; return `<div class="source-grid"><b>${n}</b><span>${a.map(x=>`${x.value} <span class="muted">(${x.source})</span>`).join('<br>')||'—'}</span><span>${a[0]?a[0].score:'—'}</span></div>`}).join('')+`<div class="scanline"><b>QR</b><span class="mono">${state.qr.length?state.qr.map(x=>x.slice(0,80)).join('<br>'):'未讀到'}</span></div><div class="scanline"><b>條碼</b><span class="mono">${state.barcodes.length?state.barcodes.join('<br>'):'未讀到／瀏覽器不支援'}</span></div>`}
async function runOCR(canvas){const logger=m=>{if(m.progress!=null){const p=Math.round(m.progress*100);bar.style.width=(35+Math.round(p*.55))+'%';status.textContent=`OCR ${p}%`}}; const worker=await Tesseract.createWorker('chi_tra+eng',1,{logger}); try{await worker.setParameters({preserve_interword_spaces:'1'}); const r1=await worker.recognize(canvas); state.ocrTexts.push(r1.data.text||''); state.ocrConfidence=Number(r1.data.confidence)||0; parseOCR(r1.data.text||'','OCR 原圖',72); chooseFields(); const criticalMissing=!seller.value||!number.value||!gross.value; if(criticalMissing||state.ocrConfidence<82){status.textContent='OCR 第二階段：影像強化…'; const enh=enhanceCanvas(canvas); const r2=await worker.recognize(enh); state.ocrTexts.push(r2.data.text||''); parseOCR(r2.data.text||'','OCR 強化',74); const bottom=cropCanvas(enh,0,Math.floor(enh.height*.42),enh.width,Math.floor(enh.height*.58)); const r3=await worker.recognize(bottom); state.ocrTexts.push(r3.data.text||''); parseOCR(r3.data.text||'','OCR 下半部',76); state.ocrConfidence=Math.max(state.ocrConfidence,Number(r2.data.confidence)||0,Number(r3.data.confidence)||0)} } finally{await worker.terminate()}}
function setFile(f,mode){if(!f)return; state.file=f;state.mode=mode;preview.src=URL.createObjectURL(f);preview.style.display='block';scan.disabled=false;status.textContent=mode==='purchase'?'已選擇「進項」上傳；此分類只作提示，不會自動填統編。':mode==='sales'?'已選擇「銷項」上傳；此分類只作提示，不會自動填統編。':'照片已載入，將依統編自動判斷。';scanSummary.textContent='準備辨識。'}
camera.onchange=e=>setFile(e.target.files[0],'auto');purchase.onchange=e=>setFile(e.target.files[0],'purchase');sales.onchange=e=>setFile(e.target.files[0],'sales');
scan.onclick=async()=>{if(!state.file)return; scan.disabled=true; state.sources={};state.candidates={};state.qr=[];state.barcodes=[];state.ocrTexts=[];state.qrBuyerAbsent=false; raw.value=''; ['date','track','number','seller','buyer','net','tax','gross'].forEach(k=>{$(k).value='';setSource(k,'—')});direction.value='unknown';direction.disabled=true;bar.style.width='5%';status.textContent='載入影像…';try{const canvas=await imageToCanvas(state.file);bar.style.width='12%';status.textContent='掃描 QR Code…';state.qr=scanQRCodes(canvas);for(const q of state.qr)addQR(q);bar.style.width='22%';status.textContent='掃描一維條碼…';state.barcodes=await scanBarcodes(canvas);for(const b of state.barcodes)addBarcode(b);chooseFields();bar.style.width='35%';status.textContent='啟動 OCR…';await runOCR(canvas);chooseFields();raw.value=state.ocrTexts.join('\n\n--- OCR PASS ---\n\n');ocrConfidence.textContent=`OCR 最佳信心 ${Math.round(state.ocrConfidence)}%`;const v=validateRecognition();renderSourceDetail();scanSummary.className=state.qr.length?'ok':'info';scanSummary.textContent=state.qr.length?`✓ 已讀到 ${state.qr.length} 個 QR Code，並完成 OCR 交叉驗證。`:'未讀到可解析的 QR Code，已使用 OCR 多階段辨識。';bar.style.width='100%';status.textContent=`辨識完成：品質 ${v.score}/100，請人工核對。`;}catch(e){status.textContent='辨識失敗：'+(e.message||e);bar.style.width='0';}finally{scan.disabled=false}};
function currentItem(){const v=validateRecognition();return {status:v.eligible?'eligible':(v.role==='ineligible'?'ineligible':'review'),direction:v.role,date:date.value,track:track.value.trim().toUpperCase(),number:fixDigits(number.value),seller:fixDigits(seller.value),buyer:fixDigits(buyer.value),net:N(net.value),tax:N(tax.value),gross:N(gross.value),ded:ded.value,quality:v.score}}
add.onclick=()=>{const it=currentItem(); if(!it.track||!it.number){alert('請先確認發票號碼');return} if(state.items.some(x=>x.track===it.track&&x.number===it.number)){alert('疑似重複發票：本期已存在相同字軌號碼');return} if(it.status==='eligible'&&it.direction==='purchase'&&it.ded==='review'){alert('進項發票請先確認可扣抵／不可扣抵');return} state.items.push(it);renderItems();calc401();conflicts.className='ok';conflicts.textContent='✓ 已依人工確認結果加入本期資料。'};
recheck.onclick=()=>{validateRecognition();renderSourceDetail()};
function renderItems(){const dl={1:'可扣抵費用',2:'可扣抵資產',3:'不可扣抵費用',4:'不可扣抵資產',review:'待確認'}; rows.innerHTML=state.items.map((x,i)=>`<tr><td><span class="pill">${x.status==='eligible'?'可申報':x.status==='ineligible'?'不可申報':'待確認'}</span></td><td>${x.direction==='purchase'?'進項':x.direction==='sales'?'銷項':'—'}</td><td>${x.date||'—'}</td><td>${x.track}${x.number}</td><td>${x.seller||'—'}</td><td>${x.buyer||'—'}</td><td>${money(x.net)}</td><td>${money(x.tax)}</td><td>${x.direction==='purchase'?(dl[x.ded]||'—'):'—'}</td><td><button class="btn ghost" onclick="delItem(${i})">刪除</button></td></tr>`).join('')}
window.delItem=i=>{state.items.splice(i,1);renderItems();calc401()};
function calc401(){const out=state.items.filter(x=>x.status==='eligible'&&x.direction==='sales').reduce((s,x)=>s+N(x.tax),0),inp=state.items.filter(x=>x.status==='eligible'&&x.direction==='purchase'&&(x.ded==='1'||x.ded==='2')).reduce((s,x)=>s+N(x.tax),0),c=N(credit.value),pay=Math.max(0,out-inp-c),carry=Math.max(0,inp+c-out);f101.textContent=money(out);f107.textContent=money(inp);f108.textContent=money(c);f111.textContent=money(pay);f112.textContent=f115.textContent=money(carry)}
credit.oninput=calc401;reset.onclick=()=>{if(confirm('清除本期測試資料？')){state.items=[];renderItems();calc401()}};
const KEY='taxAiV031Company';function loadCompany(){try{const o=JSON.parse(localStorage.getItem(KEY)||'null');if(o){companyName.value=o.name||'';companyBan.value=o.ban||'';credit.value=o.credit||0;companyMsg.className='ok';companyMsg.textContent='✓ 已載入申報單位資料。';calc401()}}catch{}}
saveCompany.onclick=()=>{const b=fixDigits(companyBan.value);if(!validBan(b)){companyMsg.className='bad';companyMsg.textContent='統一編號格式或檢查碼不正確。';return}companyBan.value=b;localStorage.setItem(KEY,JSON.stringify({name:companyName.value.trim(),ban:b,credit:N(credit.value)}));companyMsg.className='ok';companyMsg.textContent='✓ 已儲存。之後以此統編自動判斷進項／銷項／不可申報。';if(state.file)validateRecognition()};
['seller','buyer','track','number','net','tax','gross','date'].forEach(id=>$(id).addEventListener('input',()=>validateRecognition()));companyBan.addEventListener('input',()=>{if(state.file)validateRecognition()});
loadCompany();renderItems();calc401();validateRecognition();renderSourceDetail();
