const STATES=['IDLE','COLLECTING','READY_TO_SEARCH','SEARCHED','DRAFTED','REVIEW_REQUIRED','BOOKING_TASK','COMPLETED'];
const D=['TRANSPORT','ACCOM','ATTRACTION','FOOD','SHOP'],DZ={TRANSPORT:'行',ACCOM:'宿',ATTRACTION:'遊',FOOD:'食',SHOP:'購'};
const AUTH=[['TRANSPORT','HighSpeedRail','高速鐵路','TransportMode'],['TRANSPORT','Rail','鐵路','TransportMode'],['ACCOM','AC-PT-001','飯店','PropertyType'],['ACCOM','AC-PT-007','民宿','PropertyType'],['ACCOM','AC-PT-009','青年旅館','PropertyType'],['ATTRACTION','TWESG.POI.CT01','古蹟','CulturalType'],['ATTRACTION','TWESG.POI.CT05','老街','CulturalType'],['FOOD','TWESG-FB-01-07','台菜餐廳','Cuisine'],['FOOD','TWESG-FB-08-01','小吃','FoodCategory'],['SHOP','TWESG.SHOP.ST10','夜市','StoreType'],['SHOP','TWESG.SHOP.ST11','商圈／購物街區','StoreType']];
const C={TRANSPORT:[['T1','台北 → 台南｜高鐵',1350,'HighSpeedRail','高速鐵路'],['T2','台北 → 台南｜臺鐵',738,'Rail','鐵路']],ACCOM:[['A1','府城中心示範飯店｜雙人房 2 晚',5800,'AC-PT-001','飯店'],['A2','安平巷弄示範民宿｜雙人房 2 晚',4200,'AC-PT-007','民宿'],['A3','台南車站青年旅館｜2 晚',2400,'AC-PT-009','青年旅館']],ATTRACTION:[['P1','安平古堡',70,'TWESG.POI.CT01','古蹟'],['P2','安平老街',0,'TWESG.POI.CT05','老街']],FOOD:[['F1','府城台菜晚餐｜示範餐廳',1200,'TWESG-FB-01-07','台菜餐廳'],['F2','台南小吃巡禮｜示範組合',800,'TWESG-FB-08-01','小吃']],SHOP:[['S1','台南夜市購物與小吃',800,'TWESG.SHOP.ST10','夜市'],['S2','中西區商圈散策',600,'TWESG.SHOP.ST11','商圈／購物街區']]};
const PRE=['2026/9/18 到 9/20，兩人從台北去台南三天兩夜，預算兩萬元，搭高鐵、住民宿，想吃台菜和台南小吃、逛安平古堡與安平老街，晚上去夜市。','住宿改成飯店，其他不變。','再加入夜市購物。','幫我確認行程並準備預訂。'];
let active='TRANSPORT',events=[],s=fresh();
function fresh(){return{tripId:'TRIP-'+Math.random().toString(36).slice(2,8).toUpperCase(),version:1,phase:'IDLE',criteria:{origin:'',destination:'',startDate:'',endDate:'',partySize:null,budgetMax:null,currency:'TWD',needs:[]},semantic:'#a_TW #y_TWD',selected:{TRANSPORT:[],ACCOM:[],ATTRACTION:[],FOOD:[],SHOP:[]},itinerary:[],itineraryDirty:false,quote:0,review:{required:false,confirmed:false},task:null}}
function ev(kind,title,payload,level='ok'){events.unshift({time:new Date().toLocaleTimeString('zh-TW',{hour12:false}),kind,title,payload,level})}
function log(kind,title,payload,level='ok'){ev(kind,title,payload,level);render()}
function trans(next,reason){const legal={IDLE:['COLLECTING'],COLLECTING:['READY_TO_SEARCH'],READY_TO_SEARCH:['SEARCHED'],SEARCHED:['DRAFTED'],DRAFTED:['REVIEW_REQUIRED'],REVIEW_REQUIRED:['DRAFTED','BOOKING_TASK'],BOOKING_TASK:['COMPLETED'],COMPLETED:[]};if(next===s.phase)return true;if(!(legal[s.phase]||[]).includes(next)){log('GUARD','非法狀態轉移被拒絕',{from:s.phase,to:next,reason},'error');return false}const from=s.phase;s.phase=next;s.version++;ev('STATE',from+' → '+next,{reason,version:s.version});return true}
function missing(){const c=s.criteria,m=[];if(!c.destination)m.push('destination');if(!c.startDate)m.push('startDate');if(!c.endDate)m.push('endDate');if(!c.partySize)m.push('partySize');return m}
function semantic(){const c=s.criteria,a=['#a_TW'];if(c.origin)a.push('#o_'+(c.origin==='台北'?'Taipei':c.origin));if(c.destination)a.push('#p_'+(c.destination==='台南'?'Tainan':c.destination));if(c.startDate)a.push('#d_'+c.startDate);if(c.endDate)a.push('#d_'+c.endDate);if(c.partySize)a.push('#n_'+c.partySize);if(c.budgetMax)a.push('#b_'+c.budgetMax);a.push('#y_TWD');c.needs.forEach(x=>a.push('#need_'+x.toLowerCase()));s.semantic=a.join(' ')}
function parse(t){let o={};if(t.includes('台北'))o.origin='台北';if(t.includes('台南'))o.destination='台南';let ds=[...t.matchAll(/(?:2026[\/\-])?(\d{1,2})[\/\-](\d{1,2})/g)].map(x=>'2026-'+String(x[1]).padStart(2,'0')+'-'+String(x[2]).padStart(2,'0'));if(ds[0])o.startDate=ds[0];if(ds[1])o.endDate=ds[1];if(/兩人|兩個人/.test(t))o.partySize=2;let p=t.match(/(\d+)\s*人/);if(p)o.partySize=+p[1];if(/兩萬/.test(t))o.budgetMax=20000;let b=t.match(/(?:預算|提高到)\s*(\d{4,6})/);if(b)o.budgetMax=+b[1];let n=[];if(/高鐵|臺鐵|交通/.test(t))n.push('TRANSPORT');if(/飯店|民宿|住宿/.test(t))n.push('ACCOM');if(/古堡|老街|景點|安平/.test(t))n.push('ATTRACTION');if(/台菜|小吃|吃|美食/.test(t))n.push('FOOD');if(/夜市|購物|商圈/.test(t))n.push('SHOP');if(n.length)o.needs=[...new Set(n)];o.pref=/民宿/.test(t)?'bnb':/飯店/.test(t)?'hotel':'';o.review=/確認|預訂/.test(t);return o}
function mcp(name,args){const req={jsonrpc:'2.0',id:'rpc-'+Math.random().toString(36).slice(2,8),method:'tools/call',params:{name,arguments:args,_meta:{protocolVersion:'2026-07-28',tripId:s.tripId,expectedVersion:s.version,idempotencyKey:'idem-'+Math.random().toString(36).slice(2,8)}}};ev('MCP',name,req);return command(name,args)}
function markDirty(reason){if(['DRAFTED','REVIEW_REQUIRED'].includes(s.phase)){s.itineraryDirty=true;s.review={required:false,confirmed:false};if(s.phase==='REVIEW_REQUIRED')trans('DRAFTED',reason||'行程內容已變更，需重新確認');else ev('STATE','Itinerary marked dirty',{reason},'warn')}}
function price(){s.quote=Object.values(s.selected).flat().reduce((z,x)=>z+(x?x[2]:0),0)}
function command(n,a){
 if(n==='trip.set_criteria'){
  const oldNeeds=[...s.criteria.needs],{needs,...rest}=a;if(s.phase==='IDLE')trans('COLLECTING','收到意圖');Object.assign(s.criteria,rest);if(needs)s.criteria.needs=[...new Set([...oldNeeds,...needs])];s.version++;semantic();if(!missing().length&&s.phase==='COLLECTING')trans('READY_TO_SEARCH','必要欄位完成');
 }
 if(n==='catalog.search'&&s.phase==='READY_TO_SEARCH')trans('SEARCHED','候選搜尋完成');
 if(n==='trip.select'){
  const x=C[a.domain].find(v=>v[0]===a.id);if(!x)return;const before=JSON.stringify(s.selected[a.domain]);if(['TRANSPORT','ACCOM'].includes(a.domain))s.selected[a.domain]=[x];else if(!s.selected[a.domain].some(v=>v[0]===a.id))s.selected[a.domain].push(x);if(before!==JSON.stringify(s.selected[a.domain])){markDirty(a.domain+' selection changed');s.version++;price()}
 }
 if(n==='trip.clear'){
  const changed=s.selected[a.domain].length>0;s.selected[a.domain]=[];if(changed){markDirty(a.domain+' cleared');s.version++;price()}
 }
 if(n==='itinerary.build'){
  const items=Object.entries(s.selected).flatMap(([d,v])=>v.map(x=>({domain:d,id:x[0],name:x[1],authority:x[3],price:x[2]})));if(!items.length){log('GUARD','無法建立空白行程',{},'warn');return}s.itinerary=items;s.itineraryDirty=false;s.review={required:false,confirmed:false};if(s.phase==='SEARCHED')trans('DRAFTED','建立行程草稿');else s.version++;price();ev('STATE','Itinerary composed',{items:items.length,total:s.quote})
 }
 if(n==='booking.review'){
  if(s.phase!=='DRAFTED'){log('GUARD','必須先有 DRAFTED 行程才能 Review',{phase:s.phase},'warn');return}if(s.itineraryDirty){log('GUARD','行程已變更，必須先重新 compose',{itineraryDirty:true},'warn');return}s.review.required=true;trans('REVIEW_REQUIRED','交易前人類確認')
 }
 render();
}
function ensureSearch(){if(s.phase==='READY_TO_SEARCH')mcp('catalog.search',{})}
function select(d,id){mcp('trip.select',{domain:d,id})}
function auto(){ensureSearch();if(!s.selected.TRANSPORT.length)select('TRANSPORT','T1');if(!s.selected.ACCOM.length)select('ACCOM','A2');if(s.criteria.needs.includes('ATTRACTION')&&!s.selected.ATTRACTION.length){select('ATTRACTION','P1');select('ATTRACTION','P2')}if(s.criteria.needs.includes('FOOD')&&!s.selected.FOOD.length){select('FOOD','F1');select('FOOD','F2')}if(s.criteria.needs.includes('SHOP')&&!s.selected.SHOP.length)select('SHOP','S1')}
function build(){if(missing().length){msg('system','Guard：還缺 '+missing().join('、'));return}auto();mcp('itinerary.build',{})}
function confirmBooking(){if(s.phase==='SEARCHED')build();if(s.phase==='DRAFTED'&&s.itineraryDirty)mcp('itinerary.build',{});if(s.phase==='DRAFTED')mcp('booking.review',{});else if(s.phase==='REVIEW_REQUIRED'){if(!document.getElementById('human').checked){log('GUARD','Human Guard 尚未確認',{},'error');return}s.review.confirmed=true;trans('BOOKING_TASK','建立模擬 Task');s.task={id:'task-'+Date.now(),status:'running',progress:0};render();setTimeout(()=>{s.task.progress=60;s.version++;render()},400);setTimeout(()=>{s.task.progress=100;s.task.status='completed';trans('COMPLETED','Demo booking completed');render()},900)}}
function send(){let e=document.getElementById('input'),t=e.value.trim();if(!t)return;msg('user',t);e.value='';let o=parse(t),criteria={};['origin','destination','startDate','endDate','partySize','budgetMax','needs'].forEach(k=>{if(o[k]!=null)criteria[k]=o[k]});if(Object.keys(criteria).length)mcp('trip.set_criteria',criteria);ensureSearch();if(o.pref==='hotel'){mcp('trip.clear',{domain:'ACCOM'});select('ACCOM','A1')}if(o.pref==='bnb'){mcp('trip.clear',{domain:'ACCOM'});select('ACCOM','A2')}if(/夜市/.test(t)&&s.phase==='SEARCHED')select('SHOP','S1');if(o.review){if(s.phase==='SEARCHED')build();if(s.phase==='DRAFTED'&&s.itineraryDirty)mcp('itinerary.build',{});if(s.phase==='DRAFTED')mcp('booking.review',{})}document.getElementById('slots').textContent=JSON.stringify(o);msg('agent',missing().length?'目前還缺：'+missing().join('、'):'已轉成 YuYi 語義與受控 MCP 命令；v1.1 會保留既有五域需求，並在 Review 前重組已修改的行程。');render()}
function preset(i){document.getElementById('input').value=PRE[i];send()}
function resetTrip(){s=fresh();events=[];document.getElementById('human').checked=false;msg('system','已建立新的 TripSession。');render()}
function msg(c,t){let e=document.createElement('div');e.className='msg '+c;e.textContent=t;let q=document.getElementById('chat');q.appendChild(e);q.scrollTop=q.scrollHeight}
function tab(id,b){document.querySelectorAll('.pane').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.righttabs button').forEach(x=>x.classList.remove('on'));document.getElementById(id).classList.add('on');b.classList.add('on')}
function render(){document.getElementById('phase').textContent=s.phase;let ci=STATES.indexOf(s.phase);document.getElementById('states').innerHTML=STATES.map((x,i)=>'<div class="st '+(i<ci?'done':i===ci?'on':'')+'">'+(i+1)+'. '+x+'</div>').join('');let c=s.criteria;document.getElementById('kv').innerHTML=[['Trip',s.tripId],['Version','v'+s.version],['路線',(c.origin||'—')+' → '+(c.destination||'—')],['日期',(c.startDate||'—')+' ~ '+(c.endDate||'—')],['人數',c.partySize?c.partySize+' 人':'—'],['預算',c.budgetMax?'NT$'+c.budgetMax.toLocaleString():'—']].map(x=>'<div><b>'+x[0]+'</b>'+x[1]+'</div>').join('');document.getElementById('domains').innerHTML=D.map(x=>'<button class="btn '+(active===x?'on':'')+'" onclick="active=\''+x+'\';render()">'+DZ[x]+' '+x+'</button>').join('');document.getElementById('cands').innerHTML=C[active].map(x=>{let z=s.selected[active].some(v=>v[0]===x[0]);return'<div class="cand '+(z?'sel':'')+'"><b>'+x[1]+'</b><br><small>Authority: '+x[3]+' · '+x[4]+'</small><div class="row"><b>NT$'+x[2].toLocaleString()+'</b><button class="btn '+(z?'ok':'')+'" onclick="select(\''+active+'\',\''+x[0]+'\')">'+(z?'已選擇':'選擇')+'</button></div></div>'}).join('');document.getElementById('summary').innerHTML=Object.entries(s.selected).flatMap(([d,v])=>v.map(x=>'<div>'+DZ[d]+'｜'+x[1]+'　NT$'+x[2].toLocaleString()+'</div>')).join('')||'<div>尚未選擇</div>';document.getElementById('total').textContent='NT$'+s.quote.toLocaleString();document.getElementById('sem').textContent=s.semantic;document.getElementById('json').textContent=JSON.stringify(s,null,2);document.getElementById('eventlog').innerHTML=events.map(e=>'<div class="evt"><b>'+e.time+' · '+e.kind+' · '+e.title+'</b><br>'+JSON.stringify(e.payload)+'</div>').join('')||'尚無事件';document.getElementById('auth').innerHTML=AUTH.map(x=>'<div class="cand"><b>'+DZ[x[0]]+'｜'+x[2]+'</b><br><small>'+x[1]+' · '+x[3]+'</small></div>').join('')}
document.getElementById('input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});msg('agent','您好，我是 OTAA YuYi 旅遊顧問 v1.1。請先按「三天兩夜完整需求」測試。');msg('system','UI 與自然語言只會透過受控 MCP 命令改變同一份 TripSession Snapshot。');render();