(function(){
  const $=id=>document.getElementById(id); const scanBtn=$('scan'); if(!scanBtn)return;
  const DEFAULT_BACKEND='https://tax-ai-v1-gateway.vercel.app';
  const subtitle=document.querySelector('.top .muted'); if(subtitle)subtitle.textContent='V1.1｜Vercel 免費 HTTPS＋OpenAI Direct Vision＋人工確認';
  const hero=document.querySelector('.hero'); if(hero)hero.innerHTML='<b>V1.1：</b>Vercel 僅作免費 HTTPS Backend，<b>完全停用 Vercel AI Gateway</b>；手寫發票影像直接交給 OpenAI Vision。買受人統編仍以左上 8 格逐格辨識，結果必須人工確認。';
  scanBtn.textContent='✨ V1.1：本地辨識＋Direct VLM 交叉驗證';
  const card=document.createElement('div'); card.className='card section'; card.id='apiOcrV1Card';
  card.innerHTML=`<div class="section-title"><div><h2>🧠 1.1 VLM Backend｜OpenAI Direct</h2><div class="muted">Vercel AI Gateway：停用。Vercel 只負責 HTTPS；OpenAI API Key 只存在本頁記憶體，不寫入 GitHub 或 LocalStorage。</div></div><span id="apiOcrV1Badge" class="pill">等待 API Key</span></div>
  <div class="form" style="margin-top:12px"><div class="field full"><label>免費 HTTPS Backend</label><input id="apiOcrV1Url" readonly></div><div class="field"><label>Vision 模型</label><select id="apiOcrV1Model"><option value="gpt-5">gpt-5（官方 Vision 範例）</option><option value="gpt-5.6-sol">gpt-5.6-sol（最高準確優先）</option><option value="gpt-5.6-terra">gpt-5.6-terra</option><option value="gpt-5.6-luna">gpt-5.6-luna（成本優先）</option></select></div><div class="field"><label>OpenAI API Key（本次工作階段）</label><input id="apiOcrV1Key" type="password" autocomplete="off" placeholder="sk-proj-…"></div></div>
  <div class="actions" style="margin-top:10px"><button id="apiOcrV1Health" class="btn secondary">檢查 Direct VLM</button><button id="apiOcrV1Run" class="btn primary">🚀 Direct VLM 辨識本張發票</button></div><div id="apiOcrV1Status" class="info" style="margin-top:10px">請輸入 OpenAI API Key；Vercel AI Gateway 不再使用。</div><div id="apiOcrV1Meta" class="muted small" style="margin-top:8px"></div>`;
  const companyCard=$('companyName')?.closest('.card'); if(companyCard)companyCard.insertAdjacentElement('afterend',card); else document.querySelector('.card')?.insertAdjacentElement('afterend',card);
  const urlEl=$('apiOcrV1Url'),keyEl=$('apiOcrV1Key'),modelEl=$('apiOcrV1Model'),badge=$('apiOcrV1Badge'),st=$('apiOcrV1Status'),meta=$('apiOcrV1Meta'); urlEl.value=DEFAULT_BACKEND; modelEl.value=sessionStorage.getItem('taxAiVlmModel')||'gpt-5';
  const setStatus=(c,t)=>{st.className=c;st.textContent=t}; const headers=()=>{const k=String(keyEl.value||'').trim();return k?{'X-OpenAI-API-Key':k}:{}};
  function getFile(){try{if(typeof state!=='undefined'&&state.file)return state.file}catch{} for(const id of ['camera','purchase','sales']){const f=$(id)?.files?.[0];if(f)return f}return null}
  async function health(){if(!keyEl.value.trim()){badge.textContent='需要 API Key';setStatus('warn','請先輸入 OpenAI API Key；不會保存。');return false}badge.textContent='檢查中';setStatus('info','正在直接檢查 OpenAI VLM（不經 Vercel AI Gateway）…');try{const r=await fetch(DEFAULT_BACKEND+'/health/vlm',{headers:headers()}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||('HTTP '+r.status));badge.textContent='Direct VLM 正常';setStatus('ok',`✓ Direct VLM 已啟用；provider=${j.provider||'openai-direct'}，model=${j.model||'gpt-5'}。`);return true}catch(e){badge.textContent='Direct VLM 失敗';setStatus('warn','⚠ Direct VLM 尚未可用：'+(e.message||e));return false}}
  function addMapped(k,v,src,score){if(v===undefined||v===null||v==='')return;try{if(typeof addCandidate==='function')addCandidate(k,v,src,score)}catch{}const el=$(k);if(el)el.value=v;try{if(typeof setSource==='function')setSource(k,src)}catch{}}
  function mapInvoice(result){const d=result?.data||result||{},src=`Direct-VLM:${result?.source||'openai'}`;const inv=String(d.invoice_number||'').toUpperCase().replace(/\s/g,'');const m=inv.match(/^([A-Z]{2})-?(\d{8})$/);if(m){addMapped('track',m[1],src,200);addMapped('number',m[2],src,200)}addMapped('date',d.invoice_date,src,195);addMapped('seller',d.seller_tax_id,src,220);addMapped('buyer',d.buyer_tax_id,src,220);addMapped('net',d.sales_amount,src,195);addMapped('tax',d.tax_amount,src,195);addMapped('gross',d.total_amount,src,195);if($('sellerName')&&d.seller_name)$('sellerName').value=d.seller_name;try{if(typeof chooseFields==='function')chooseFields()}catch{}try{if(typeof validateRecognition==='function')validateRecognition()}catch{}return d}
  async function runBackend(){const file=getFile();if(!keyEl.value.trim()){badge.textContent='需要 API Key';setStatus('warn','Direct VLM 未執行：請先輸入 OpenAI API Key。');return null}if(!file){setStatus('warn','請先拍照或上傳發票。');return null}badge.textContent='Direct VLM 辨識中';setStatus('info','已送到免費 Vercel HTTPS Backend，正在直接呼叫 OpenAI Vision…');const fd=new FormData();fd.append('file',file,file.name||'invoice.jpg');fd.append('model',modelEl.value);try{const t=performance.now(),r=await fetch(DEFAULT_BACKEND+'/v1/invoice',{method:'POST',headers:headers(),body:fd}),j=await r.json().catch(()=>null);if(!r.ok)throw new Error(j?.detail||('HTTP '+r.status));if(!j?.results?.length)throw new Error('Direct VLM 未回傳結果');const first=j.results[0],d=mapInvoice(first),ms=Math.round(performance.now()-t);badge.textContent='Direct VLM 完成';setStatus('ok',`✓ 後端真正完成辨識${d.buyer_tax_id?'；買受人統編 '+d.buyer_tax_id:''}${d.seller_tax_id?'；賣方統編 '+d.seller_tax_id:''}。請對照 8 格人工確認。`);meta.textContent=`provider=${j.provider||'openai-direct'}｜model=${j.model||modelEl.value}｜confidence=${first.confidence!=null?Math.round(first.confidence*100)+'%':'—'}｜${ms}ms`;return j}catch(e){badge.textContent='Direct VLM 失敗';setStatus('warn','⚠ 後端已呼叫，但 VLM 失敗：'+(e.message||e));return null}}
  $('apiOcrV1Health').onclick=health; $('apiOcrV1Run').onclick=runBackend; modelEl.onchange=()=>sessionStorage.setItem('taxAiVlmModel',modelEl.value);
  const baseScan=scanBtn.onclick;scanBtn.onclick=async function(){if(typeof baseScan==='function')await baseScan.call(scanBtn);await runBackend()};
})();
